version: 0.2

phases:
  install:
    commands:
      - npm install
      - zip -r code.zip .
  post_build:
    finally:
      - aws lambda update-function-code --function-name 0x4447_product_ec2_hibernation_lambda --zip-file fileb://./code.zip
